#the maximum number of coingecko tokens is 6

wallets:
  ['Phantom', 'Keplr', 'Metamask', 'Sui', 'OKX', 'Total']
metrics:
  ['Portfolio value', 'Absolute ROI', 'PnL day', 'Rewards']

phantom:
  run_meteora: False
  ticker_coingecko: ['SWTCH']

phantom2:
  ticker_coingecko: []

solflare:
  ticker_coingecko: []

solflare2:
  ticker_coingecko: []

backpack:
  ticker_coingecko: []

metamask:
  ticker_coingecko: ['EIGEN']

okx:
  ticker_coingecko: ['KAITO']

seeker:
  ticker_coingecko: []

phantom tablet 1:
  ticker_coingecko: []

phantom tablet 2:
  ticker_coingecko: []

solflare tablet 1:
  ticker_coingecko: []

solflare tablet 2:
  ticker_coingecko: []

slush laptop 1:
  ticker_coingecko: []

slush laptop 2:
  ticker_coingecko: []

backpack laptop 1:
  ticker_coingecko: []

backpack laptop 2:
  ticker_coingecko: []

backpack laptop 3:
  ticker_coingecko: []

backpack laptop 4:
  ticker_coingecko: []

backpack phone 1:
  ticker_coingecko: []

backpack phone 2:
  ticker_coingecko: []

slush phone 1:
  ticker_coingecko: []

slush phone 2:
  ticker_coingecko: []

slush phone 3:
  ticker_coingecko: []

slush phone 4:
  ticker_coingecko: []

bitget:
  ticker_coingecko: ['SWTCH']

bybit:
  ticker_coingecko: ['SKATE']

photon:
  ticker_coingecko: ['CODEC']

ledger new:
  ticker_coingecko: []

monad main:
  ticker_coingecko: []

monad NFTs:
  ticker_coingecko: []

backpack mon:
  ticker_coingecko: []

kraken:
  ticker_coingecko: []








